POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "jake@jake.jake",
    "password": "123456"
}


####
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "email": "jake@jake.jake",
    "username": "jake",
    "password": "123456"

}

####

GET http://localhost:3000/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impha2UiLCJpYXQiOjE2MjgwMDI3NzIsImV4cCI6MTYyODAwNjM3Mn0.Ax7mQzCjlIBZG7o4WE9oiFGEKkEN4S7jPpkC1KUlt74

###

PUT http://localhost:3000/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impha2UiLCJpYXQiOjE2MjgwMDI3NzIsImV4cCI6MTYyODAwNjM3Mn0.Ax7mQzCjlIBZG7o4WE9oiFGEKkEN4S7jPpkC1KUlt74

{
    "bio": "xxx",
    "image": "image",
    "xxx": "hello"
}